AddonId: SteamNonSteamImporter
Packages:
  - Version: 1.0
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2025-05-30
    PackageUrl: https://github.com/Phalk/SteamNonSteamImporter/releases/download/1.0/SteamNonSteamImporter_8d105bff-eac4-45c5-90ba-c77fdd66b882_1_0.pext
    Changelog:
      - First release

AddonId: SteamNonSteamImporter_8d105bff-eac4-45c5-90ba-c77fdd66b882
Type: GameLibrary
Name: Steam Non Steam Importer
Author: Phalk
ShortDescription: Imports Steam non Steam (from Steam's shortcuts.vdf)
InstallerManifestUrl: https://raw.githubusercontent.com/Phalk/SteamNonSteamImporter/refs/heads/main/manifests/SteamNonSteamImporter.yaml
SourceUrl: https://github.com/Phalk/SteamNonSteamImporter
Links:
  Phalk's Website: https://phalk.net/
Description: |
   A Playnite plugin that imports non-Steam games from Steam shortcuts into your Playnite library.
Tags: ["nonsteam", "steam"]
IconUrl: https://raw.githubusercontent.com/Phalk/SteamNonSteamImporter/refs/heads/main/icon.png
